### ISSUE TITLE
logging may be broken

### ISSUE THREAD

**Issue by hulsiejames** [Transport-for-the-North/otp4gb-py#15]
May have overlooked something in the previous PR to main (cost_infilling)

Running process.py returns
```
(otp4gb-py) PS E:\Repos\otp4gb-py> python process.py url_check_testing
Traceback (most recent call last):
  File "E:\Repos\otp4gb-py\process.py", line 193, in <module>
    main()
  File "E:\Repos\otp4gb-py\process.py", line 76, in main
    log_file = file_handler_factory(
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Repos\otp4gb-py\otp4gb\logging.py", line 29, in file_handler_factory
    handler.setFormatter(flat_formatter)
                         ^^^^^^^^^^^^^^
NameError: name 'flat_formatter' is not defined
```

Within logging.py, flat_formatter has been commented out (for updated logger)
```
# logging.basicConfig(format=FORMAT_STRING, datefmt="%H:%M:%S")

# flat_formatter = logging.Formatter(FORMAT_STRING, "%H:%M:%S")   <-------------------------

# stderr_handler = logging.StreamHandler(stream=sys.stderr)
# stderr_handler.setFormatter(flat_formatter)


def file_handler_factory(filename, dir=LOG_DIR, level=logging.INFO):
    if not os.path.exists(dir):
        os.makedirs(dir)
    handler = logging.FileHandler(os.path.join(dir, filename), mode="w")
    handler.setFormatter(flat_formatter)
    handler.setLevel(level)
    return handler
```

within process.py, this outdated logger, which relies on `flat_formatter` is used
```
    log_file = file_handler_factory(
        f"process-{datetime.date.today():%Y%m%d}.log", arguments.folder / "logs"
    )
    logger.addHandler(log_file)
```

**Comment by wsp-mbuckley** [comment]
Should be resolved by #17 which switches to using `caf.toolkit.LogHelper`
